### ISSUE TITLE
[Requirement] Eintrag erstellen können und benutzen

### ISSUE THREAD

**Issue by ghost** [kai-oswald/ASE#11]
## Szenario: Eintrag anlegen

Ich bin Anwender
UND befinde mich auf einer Eingabemaske
WENN ich eine URL eintrage
UND bestätige
DANN erhalte ich eine gekürzte URL
## Szenario2: Gekürzte URL benutzen

Ich bin unabhängiger Anwender
WENN ich die gekürzte URL im Browser eintrage
DANN werde ich auf die entsprechende URL weitergeleitet.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by DTobii** [comment]
Currently missing:
- Check/controll URL

**Comment by Hurba** [comment]
Finished
