### ISSUE TITLE
[Requirement] Premium-Anwender unterstützen

### ISSUE THREAD

**Issue by ghost** [kai-oswald/ASE#12]
## Szenario: Als Premium-Anwender authentifizieren

Ich bin Anwender
UND befinde mich auf einer Eingabemaske für Premium-Anwender
WENN ich in der Eingabemaske einen Authentifizierungs eingebe
DANN merkt sich die Anwendung, dass ich ein Premium-Anwender bin.
## Szenario2: Authentifizierungscode für Premium-Anwender generieren

Ich bin Administrator der Anwendung
WENN ich auf eine passwortgeschützte Unterseite der Anwendung öffne
DANN generiert die Anwendung einen Premium-Anwender Authentifizierungscode
UND wird mir angezeigt.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by DTobii** [comment]
I think we should use a new datamodel (Premiumcodes) to save the codes.

**Comment by kai-oswald** [comment]
# Szenario 1
- POST an die URL: /login. Im Body der Request steht der Premiumcode.
- Überprüfen, ob Premiumcode gültig und entsprechende Antwort zurückgeben.
- Die Anwendung soll sich merken, ob jemand Premium-Nutzer ist -> Session setzen

# Szenario 2
- Neue Route: /admin, auf der man sich einloggen kann. (Ähnlich Wordpress /wp-admin)
- WENN eingeloggt: neuen Premiumcode generieren. POST an /vip.
- ZUNÄCHST auf Server überprüfen, ob authentifizierter Admin
- Antwort mit neuem VIP CODE oder Fehlermeldung

**Comment by Hurba** [comment]
> Szenario2:
> 
> Authentifizierungscode für Premium-Anwender generieren
> 
> Ich bin Administrator der Anwendung
> WENN ich auf eine passwortgeschützte Unterseite der Anwendung öffne
> DANN generiert die Anwendung einen Premium-Anwender Authentifizierungscode
> UND wird mir angezeigt.

**UND wird mir angezeigt. Is not yet Finished**

**Comment by TrAnn3l** [comment]
It gets shown as infobox and still stays in the textbox, should be enough.
