### ISSUE TITLE
[Requirement] Statistiken

### ISSUE THREAD

**Issue by ghost** [kai-oswald/ASE#13]
## Szenario: Statistik erheben

WENN eine Weiterleitung benutzt wird
DANN merkt sich die Anwendung dies für eine Eintragspezifische Statistik.
## Szenario2: Statistik anzeigen

Ich bin Anwender
WENN ich eine Detailseite des Links öffne
DANN werden mir Statistische Informationen zu diesem Eintrag angezeigt.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by DTobii** [comment]
- Link to site
- Overview of all

**Comment by Hurba** [comment]
Insert Button

**Comment by DTobii** [comment]
Should be solved. Maybe someone else can check?
