### ISSUE TITLE
[Requirement] Wunsch-URLs 

### ISSUE THREAD

**Issue by ghost** [kai-oswald/ASE#14]
## Szenario: Wunsch-URL eintragen

Ich bin Premium-Anwender
UND bin in der Eingabemaske um einen neuen Eintrag machen zu können
DANN habe ich die Möglichkeit eine Wunsch-URL eintragen zu können.
## Szenario2: Anwendungslinks sind stärker

Ich bin Premium-Anwender
UND bin in der Eingabemaske um einen neuen Eintrag zu machen
UND habe eine Wunsch-URL einetragen
UND diese Wunsch-URL entspricht einer System-URL (Anwendungsroute)
DANN erhalte ich eine Fehlermeldung angezeigt.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by kai-oswald** [comment]
# Szenario 1
- WENN Premium, dann:
- neue Eingabemaske, um Wunsch-URLs zu erstellen

# Szenario 2
- Wunsch-URL validieren (u. a. Abgleich mit vordefinierten Routen)
- entsprechende Fehlermeldung zurückgeben und anzeigen

**Comment by mlechler** [comment]
Finished
