### ISSUE TITLE
[Requirement] QR Code

### ISSUE THREAD

**Issue by ghost** [kai-oswald/ASE#15]
## Szenario: QR Code generieren

Ich bin Premium-Anwender
WENN ich einen Eintrag erstellt habe
DANN bekomme ich auch einen entsprechenden QR Code angezeigt.
## Szenario2: QR Code Benutzung tracken 

WENN der QR Code benutzt wird
DANN merkt sich die Anwendung das.
## Szenario3: QR Code Statistik anzeigen 

Ich bin Premium-Anwender
UND habe die Detailseite eines Eintrags geöffnet
DANN bekomme ich eine Statistik darüber angezeigt, wie oft der QR Code benutzt wurde.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by kai-oswald** [comment]
use: [Goqr API](http://goqr.me/de/api/doc/create-qr-code/)

# Szenario 1
- wenn PREMIUM, dann erstelle auch gleich QR beim URL kürzen
- QR in selbes Datenmodel wie gekürzte Links

# Szenario 2
- Getrenntes Tracking für QR-Codes: /qr/[ShortLink]

**Comment by DTobii** [comment]
Divide the Statistic of QR

**Comment by Hurba** [comment]
Szenario 2 finished.
Szenario 3 finished.

**Comment by TrAnn3l** [comment]
What's the progress of not showing the qr-code to normal User @Hurba ?
