### ISSUE TITLE
Idea: Special Links

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/ASE#3]
A possible feature would be "special" links. 
The normal links are random codes after the domain e.g. abc.de/<randomcode>
The special links are codes which can be selected by user e.g. abc.de/<mycode> 
This feature could be connected with Usermanagement that only registered users can use this feature.
It would be nice because it maybe makes the link more trustable then a short, cryptical link.

Comments? Ideas?

**Comment by TrAnn3l** [comment]
Dupliacted to #14
