### ISSUE TITLE
Idea: Tracking/Stats for Links

### ISSUE THREAD

**Issue by TrAnn3l** [kai-oswald/ASE#4]
A nice to have feature would be the tracking of the shortened URL for Users.
We could show some kind of graph, with views per day or sth . like that.

**Comment by kai-oswald** [comment]
Also: stats of how many links have been shortened by our service (see [bit.ly](https://bitly.com/))

**Comment by DTobii** [comment]
I would use a new Datamodel for stats. We also should use a new controllers and routes file? 
For graphs maybe we can use https://github.com/valor-software/ng2-charts? Or has anyone other suggestions? I never used a framework for graphs in angular...

**Comment by TrAnn3l** [comment]
Duplicated to #13
