### ISSUE TITLE
Stats are not working properly

### ISSUE THREAD

**Issue by TrAnn3l** [kai-oswald/ASE#41]
To test, reset your database with the following commands:
`mongo`
`use todos`
`db.dropDatabase()`
After that shorten one url.

The detail page is not showing all entries, seems like one is always missing.
Maybe an Index error?
This causes also that the stats are rendering bizarre when only one link was shortened.

**Comment by DTobii** [comment]
Detailpage = overview of all stats?
If yes: #38 should fix that at my last test and push (tested with 0-10 shortened links)

**Comment by TrAnn3l** [comment]
Fixed in #38
