### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by TrAnn3l** [kai-oswald/ASE#64]
We need 10 Unit-tests.

**Comment by DTobii** [comment]
Some proposals:

Validate URL: 

- [ ] Richtige URL
- [ ] Falsche URL

-> @TrAnn3l 

CheckLongLink:

- [x] Premium und Systemurl
- [x] Premium und keine Systemurl
- [x] Kein Premium

-> @DTobii

Create:

- [ ] Ob er erstellt wird
- [ ] (Ggf. ob die Fehlerbehandlung funktioniert)

-> @kai-oswald 

linkByShort:

- [ ] Gibt einen Shortlink
- [ ] Gibt keinen Shortlink

-> @Hurba 

CheckShortLink

- [x] ShortLink schon in Datenbank
- [x] Shortlink nicht in Datenbank

-> @mlechler

**Comment by TrAnn3l** [comment]
Ihr müsst mocha noch in eurer VM oder lokal global installieren.
#Wenn auf VM
`vagrant ssh` 
`sudo npm install mocha -g`

#Wenn lokal
`npm install mocha -g`

**Comment by TrAnn3l** [comment]
Da es Probleme mit dem testen der Middleware gibt, sollten wir vielleicht unsere Testfälle überarbeiten.

**NICHT-PREMIUM**
- [ ] URL kürzen
- [ ] URL kürzen, Weiterleitung prüfen
- [ ] Gleiche URL 2 mal kürzen, überprüfen ob shortlink bei beiden gleich ist.

**PREMIUM**
- [ ] URL kürzen ohne Shortlink
- [ ] URL kürzen ohne Shortlink, Weiterleitung prüfen
- [ ] URL kürzen mit Shortlink
- [ ] URL kürzen mit Shortlink, Weiterleitung prüfen
- [ ] URL kürzen mit Shortlink=SystemURL 
- [ ] 2 unterschiedliche URL kürzen mit gleichem shortlink

GGF erweitern

**Comment by DTobii** [comment]
node-mocks-http muss auch im vagrant noch installiert werden.

**Comment by kai-oswald** [comment]
Hab andere Testfälle bearbeitet 👻 
- Generierung von Random Text
- Erstellen des erweiterten Link-Models

**Comment by DTobii** [comment]
Currently @kai-oswald , @mlechler and my tests are merged into master. @TrAnn3l and @Hurba can you merge your tests too? Or do you need some help at the tests?
